apiVersion: manifests.package-operator.run/v1alpha1
kind: PackageManifest
metadata:
  name: addon-operator
spec:
  scopes:
    - Cluster
  phases:
    - name: namespace-crds
      class: hosted-cluster
    - name: deploy
  availabilityProbes:
    - probes:
        - condition:
            type: Available
            status: "True"
        - fieldsEqual:
            fieldA: .status.updatedReplicas
            fieldB: .status.replicas
      selector:
        kind:
          group: apps
          kind: Deployment
