# This manifest is only for testing and should be used with `00-tls-secret.yaml`
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: addon-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    # Should be used with `00-tls-secret.yaml`
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZpakNDQTNLZ0F3SUJBZ0lVSC9xQmxWdXRRNUptdFBRRlFIcy95WnJuVlNrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd056RTFNRE1HQTFVRUF3d3NkMlZpYUc5dmF5MXpaWEoyYVdObExtOXdaVzV6YUdsbWRDMWhaR1J2YmkxdgpjR1Z5WVhSdmNpNXpkbU13SGhjTk1qUXdNVEEwTURFek1ERXdXaGNOTXpRd01UQXhNREV6TURFd1dqQTNNVFV3Ck13WURWUVFEREN4M1pXSm9iMjlyTFhObGNuWnBZMlV1YjNCbGJuTm9hV1owTFdGa1pHOXVMVzl3WlhKaGRHOXkKTG5OMll6Q0NBaUl3RFFZSktvWklodmNOQVFFQkJRQURnZ0lQQURDQ0Fnb0NnZ0lCQUt3WTZycDFXZXRCd2t6ZQp6VHpiNXUwUTAvT2Fta2NUWGJuK1hDSkN0TTFoNVJ3YnhzclB2VnY4SGtOeFJaTHhRYWYvNW1OQzdmYUF5N0d5CjBwb0FmT0FhWWxMaGF3alorTmd1Zm8xbG1IYXhTNDRrT1JZdXJHZ3pIY281NEdGK0tVK1RjRG1WN2VhbWFDbEYKSjlpQjhUL2kyS1kxRDdqcEtaU0FsZUREQkxkcWtqS0ZKLzlnMzJybHZPK0YvZFBBbWdRalNqRWh5a0IyRFE4SQp6S3BKRDBSQVBxdDZ4ZXZnZlkvNmpmb3pLOGtza0FKdTBSZGRwMW5DYjVLcmRSbjA1dkhVRGNkOFBPMnI2NmNXClJJTUJUN1N3b3pwZmVrTHRabXphRmVnQW5kZFoyZGZRM3JTelBGZ1FvNzUxbGxhMitYcXl0c2dEdXMzSGl0cUwKckVZdVFPYXhZMDhsRXRNRTZGbEJMcGt0cWZWRnAydmVwZWFXWW9mMWFuUEtoSm5HZytXYnBKQ0krMFMxS2JhdwpFNFRURXM4UDdxaDdhMmVtQWhCOHJRYVJtR3NZS3F3c2o2SkRwQUlrUDQxcHZKajc5RjRTZXdRSzB1a2Npa3EwCnl2RHJKQjhUbE5YUUVmSUVNUC9ORVplb0t3NXc4NVFGNmJrNmRsdFJCbmFBN0dOVkVuRG9UaWQ0b0ZmekV1YXQKSkZFYWkrbUQrakxXdWEyZ2NHR2pWV1E0aGI0T0dqUmlwR1d5U2JRTVdYc0lvQ3k1dkJacVJhZHpoYWlybDR5UQpFQ1VQOFE1aGg2SCtCMENnS2NCRWJUYWtWZ3hlY3RwaG1qcjhpeGpiY0tURllNWXkvSzM2bnFLSnpDVThLRE9FCkR0Mm9ibTFxOEM2dGZ3VHZDYXRaaEtSd0VWa2hBZ01CQUFHamdZMHdnWW93SFFZRFZSME9CQllFRk0vaTdzV24KV2VVLy9wZHRtRVMrYjhMQXliNDBNQjhHQTFVZEl3UVlNQmFBRk0vaTdzV25XZVUvL3BkdG1FUytiOExBeWI0MApNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdOd1lEVlIwUkJEQXdMb0lzZDJWaWFHOXZheTF6WlhKMmFXTmxMbTl3ClpXNXphR2xtZEMxaFpHUnZiaTF2Y0dWeVlYUnZjaTV6ZG1Nd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dJQkFGU1UKMUU2WkJRVFRYNkdveWNISFczc1hQWEhSZFNsYjUzVGR2NHgyM2FheE12YjUya0RESlFnT3NicFI0cTRGbXdQLwpmLzNtYWU2VFpEcituS2dWVmw3QXJjN3FGcENRcDV2SEVaZHZVcERRbE9BOHpiM2FLdy9Ua3JwTFluUWE5N1NyCm0wbzlkaHhNWkJlb1QxQ3VtSHVCMndhTEZZd0lMbWQ0eHA2ald6NnBkNTdqaXY3bnhWUVZlYjdkdWRZYklYQlcKR2hnUWdadFRYbWFnQ1lOTC9ZOGd2N1o2THhhYThVOWdxeWJIOFpNSTBCN25iRjdzRG5VZGZid1FpdVZDelV4Nwp0cEtlQTdjc28zdlRkQTNaSFNTVERuMmttMlNza1JHampIZERkZHlmUFo1cXp4bkkxYzd4Tlp3U2RKbW5sZWtDCm5SWmlnUFFWWHc4ZHZFTWVDMkxsMXV3dEJLNERZVkZxYVlNaG4rczBqenhJUVZBTzNCNjZrdEg1dEZZanlsTTYKK2JDVm8vQ01UTmNYZTFjMUhWTmloZEZKZDdiVWpycFc3M1lEY3EydUNnMHQzanVkMzV5RVFidnY3VkFsUFJOTApVWmJRaGx0a0FyZ2YvUWdGeGN2UE1xY3U0cEsrdS81V1lsOTMrTU1reXZGbWh3NmVSUVJySHQzL1NZTFB2eXI4Cmdrcys2bUYyazYvSEJOUk9CQWtoNzkvSWozcy9kVDRyUmwzU1lXcGh4ZzRWT00xRUlSVEhHbEZWdFEzYTZMMkUKLzlBTkZJRXhhQTd0MkJIcHNSVU5MM29WU0IvMFJ1RjdQTHBjOGtvMzEwYWpJc2VEWXJKdE5MNThDQ2VWYTFlMgptQlNYbEFtTjhCL2pNMkI2UFF3OTNRdXNob1huOStJSU9ETldWeDhFCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K 
    service:
      name: webhook-service
      namespace: openshift-addon-operator
      path: /validate-addon
  failurePolicy: Fail
  name: vaddons.managed.openshift.io
  rules:
  - apiGroups:
    - addons.managed.openshift.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - addons
  sideEffects: None
