# To be used for local development and testing only
apiVersion: v1
kind: Service
metadata:
  name: addon-operator-metrics
  namespace: addon-operator
  labels:
    app: addon-operator-metrics-service
spec:
  ports:
    - port: 8080
      name: public
      targetPort: 8080
    - port: 8083
      name: private  ## [only for dev/test purposes], wouldn't work if --enable-metrics-tls-termination=false
      targetPort: 8083
  selector:
    app.kubernetes.io/name: addon-operator
