# To be used for local development and testing only
apiVersion: v1
kind: Service
metadata:
  name: addon-operator-metrics
  namespace: addon-operator
  labels:
    app: addon-operator-metrics-service
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 8080
    - port: 8083
      name: https
      targetPort: 8083
  selector:
    app.kubernetes.io/name: addon-operator
