# To be used for local development and testing only
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: addon-operator-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - addon-operator
  selector:
    matchLabels:
      app: addon-operator-metrics-service
  endpoints:
    ### TODO: get rid of `port: private` in the future
    - port: private
      interval: 10s
      path: /metrics
    - port: public
      interval: 10s
      path: /metrics
      tlsConfig:
        insecureSkipVerify: true
        ### ALERT! - Only use insecureSkipVerify: true for test / dev environment
        ### For production-grade environment, it's recommended to have a dedicated secret injected with TLS config
        ### and that secret should be fed to the service monitor's tls config like the following way:
        # ca:
        #   secret:
        #     name: <secret-name-containing-tls-config>
        #     key: ca.crt
        #     optional: false
        # cert:
        #   secret:
        #     name: <secret-name-containing-tls-config>
        #     key: tls.crt
        #     optional: false
        # keySecret:
        #   name: <secret-name-containing-tls-config>
        #   key: tls.key
        #   optional: false
