# To be used for local development and testing only
apiVersion: v1
kind: Service
metadata:
  name: addon-operator-metrics
  namespace: addon-operator
  labels:
    app: addon-operator-metrics-service
spec:
  ports:
    - port: 8443
      name: https
      targetPort: 8443
    - port: 8080
      name: http  ## [only for dev/test purposes]
      targetPort: 8080
  selector:
    app.kubernetes.io/name: addon-operator
